# Generated by Django 3.0 on 2021-05-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dea',
            name='y_utm',
            field=models.IntegerField(default=None),
        ),
    ]
